import { Lead, Message, Stats, ContractorSettings } from './api';

export const PREVIEW_LEADS: Lead[] = [
  {
    id: 'preview-1',
    full_name: 'Sarah Mitchell',
    phone: '+1 (214) 555-0138',
    email: 'sarah.mitchell@gmail.com',
    zip_code: '75034',
    address: '6824 Windward Way, Frisco, TX',
    issue_type: 'ACTIVE_LEAK',
    roof_age: '10-20 years',
    has_insurance_claim: false,
    status: 'NEW',
    source: 'MISSED_CALL',
    ai_auto_respond: true,
    inspection_date: null,
    inspection_notes: 'Urgent: Water dripping into master closet ceiling near chimney. Tarp requested.',
    quote_amount: null,
    job_value: null,
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 'preview-2',
    full_name: 'Michael Chang',
    phone: '+1 (469) 555-0129',
    email: 'm.chang88@outlook.com',
    zip_code: '75070',
    address: '2210 Stonebridge Dr, McKinney, TX',
    issue_type: 'STORM_DAMAGE',
    roof_age: 'Under 10 years',
    has_insurance_claim: false,
    status: 'NEW',
    source: 'LANDING_PAGE',
    ai_auto_respond: true,
    inspection_date: null,
    inspection_notes: 'Quarter-sized hail reported after Tuesday severe thunderstorm.',
    quote_amount: null,
    job_value: null,
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 'preview-3',
    full_name: 'Brad Hollister',
    phone: '+1 (972) 555-0145',
    email: 'bhollister@verizon.net',
    zip_code: '75013',
    address: '1405 Watters Creek Blvd, Allen, TX',
    issue_type: 'AGING_ROOF_REPLACEMENT',
    roof_age: '20+ years',
    has_insurance_claim: false,
    status: 'NEW',
    source: 'GOOGLE',
    ai_auto_respond: true,
    inspection_date: null,
    inspection_notes: '22-year-old 3-tab shingle roof. Heavy granule loss in gutters.',
    quote_amount: null,
    job_value: null,
    created_at: new Date(Date.now() - 55 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 55 * 60000).toISOString(),
  },
  {
    id: 'preview-4',
    full_name: 'Marcus Johnson',
    phone: '+1 (469) 555-0172',
    email: 'marcus.johnson@txmail.com',
    zip_code: '75024',
    address: '5401 Legacy Dr, Plano, TX',
    issue_type: 'STORM_DAMAGE',
    roof_age: 'Under 10 years',
    has_insurance_claim: true,
    status: 'AI_QUALIFYING',
    source: 'LANDING_PAGE',
    ai_auto_respond: true,
    inspection_date: null,
    inspection_notes: 'AI qualified State Farm claim #SF-98421. Homeowner reported hail indentations on gutters.',
    quote_amount: null,
    job_value: null,
    created_at: new Date(Date.now() - 95 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 'preview-5',
    full_name: 'Stephanie Ross',
    phone: '+1 (214) 555-0193',
    email: 'sross.dallas@gmail.com',
    zip_code: '75248',
    address: '7712 Campbell Rd, Dallas, TX',
    issue_type: 'ACTIVE_LEAK',
    roof_age: '10-20 years',
    has_insurance_claim: false,
    status: 'AI_QUALIFYING',
    source: 'MISSED_CALL',
    ai_auto_respond: true,
    inspection_date: null,
    inspection_notes: 'AI gathered leak location (upstairs hallway skylight) and requested photo upload.',
    quote_amount: null,
    job_value: null,
    created_at: new Date(Date.now() - 140 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 60000).toISOString(),
  },
  {
    id: 'preview-6',
    full_name: 'Greg Sullivan',
    phone: '+1 (972) 555-0181',
    email: 'greg.sullivan@techfirm.com',
    zip_code: '75035',
    address: '9104 Eldorado Pkwy, Frisco, TX',
    issue_type: 'AGING_ROOF_REPLACEMENT',
    roof_age: '20+ years',
    has_insurance_claim: true,
    status: 'AI_QUALIFYING',
    source: 'REFERRAL',
    ai_auto_respond: true,
    inspection_date: null,
    inspection_notes: 'Interested in Class 4 Impact Resistant shingles for insurance premium discount.',
    quote_amount: null,
    job_value: null,
    created_at: new Date(Date.now() - 180 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 'preview-7',
    full_name: 'Emily Carter',
    phone: '+1 (972) 555-0194',
    email: 'emily.carter@dfwhomes.net',
    zip_code: '75093',
    address: '3819 Willow Bend Dr, West Plano, TX',
    issue_type: 'ROOF_REPLACEMENT',
    roof_age: '20+ years',
    has_insurance_claim: false,
    status: 'INSPECTION_SCHEDULED',
    source: 'REFERRAL',
    ai_auto_respond: false,
    inspection_date: new Date(Date.now() + 86400000).toISOString(),
    inspection_notes: 'Inspection confirmed for tomorrow at 10:00 AM with Estimator Marcus. Drone survey requested.',
    quote_amount: null,
    job_value: null,
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'preview-8',
    full_name: 'Robert Henderson',
    phone: '+1 (469) 555-0158',
    email: 'rhenderson@telecom.net',
    zip_code: '75082',
    address: '1904 Breckinridge Blvd, Richardson, TX',
    issue_type: 'STORM_DAMAGE',
    roof_age: '10-20 years',
    has_insurance_claim: true,
    status: 'INSPECTION_SCHEDULED',
    source: 'GOOGLE',
    ai_auto_respond: false,
    inspection_date: new Date(Date.now() + 110000000).toISOString(),
    inspection_notes: 'Allstate adjuster walkthrough scheduled for tomorrow at 2:30 PM. Estimator Marcus attending.',
    quote_amount: null,
    job_value: null,
    created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'preview-9',
    full_name: 'Kevin Nguyen',
    phone: '+1 (214) 555-0119',
    email: 'knguyen@carrolltontx.org',
    zip_code: '75007',
    address: '1422 Kelly Blvd, Carrollton, TX',
    issue_type: 'ACTIVE_LEAK',
    roof_age: '10-20 years',
    has_insurance_claim: false,
    status: 'INSPECTION_SCHEDULED',
    source: 'MISSED_CALL',
    ai_auto_respond: false,
    inspection_date: new Date(Date.now() + 172800000).toISOString(),
    inspection_notes: 'Inspection booked for Wednesday at 11:00 AM. Suspected pipe flashing gasket crack.',
    quote_amount: null,
    job_value: null,
    created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'preview-10',
    full_name: 'David Ramirez',
    phone: '+1 (214) 555-0166',
    email: 'david.ramirez@dallascivil.org',
    zip_code: '75001',
    address: '4115 Belt Line Rd, Addison, TX',
    issue_type: 'STORM_DAMAGE',
    roof_age: '10-20 years',
    has_insurance_claim: true,
    status: 'QUOTE_SENT',
    source: 'GOOGLE',
    ai_auto_respond: false,
    inspection_date: new Date(Date.now() - 86400000).toISOString(),
    inspection_notes: 'Drone hail scan completed. $18,450 itemized proposal sent via SMS link.',
    quote_amount: 18450,
    job_value: null,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: 'preview-11',
    full_name: 'Patricia Davis',
    phone: '+1 (972) 555-0177',
    email: 'patricia.davis@prosperisd.net',
    zip_code: '75078',
    address: '801 First St, Prosper, TX',
    issue_type: 'ROOF_REPLACEMENT',
    roof_age: '20+ years',
    has_insurance_claim: false,
    status: 'QUOTE_SENT',
    source: 'REFERRAL',
    ai_auto_respond: false,
    inspection_date: new Date(Date.now() - 2 * 86400000).toISOString(),
    inspection_notes: '38 squares architectural shingle replacement with seamless gutter upgrade.',
    quote_amount: 24200,
    job_value: null,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
  {
    id: 'preview-12',
    full_name: 'Jennifer Lee',
    phone: '+1 (469) 555-0113',
    email: 'jennifer.lee@friscotx.gov',
    zip_code: '75035',
    address: '7204 Stonebrook Pkwy, Frisco, TX',
    issue_type: 'ROOF_REPLACEMENT',
    roof_age: '20+ years',
    has_insurance_claim: true,
    status: 'JOB_WON',
    source: 'REFERRAL',
    ai_auto_respond: false,
    inspection_date: new Date(Date.now() - 4 * 86400000).toISOString(),
    inspection_notes: 'E-Contract signed! 50% deposit received ($11,890). Tear-off scheduled for Friday.',
    quote_amount: 23780,
    job_value: 23780,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'preview-13',
    full_name: 'Brian O\'Connor',
    phone: '+1 (214) 555-0182',
    email: 'brian.oconnor@lakefront.com',
    zip_code: '75068',
    address: '2908 Eldorado Pkwy, Little Elm, TX',
    issue_type: 'STORM_DAMAGE',
    roof_age: '10-20 years',
    has_insurance_claim: true,
    status: 'JOB_WON',
    source: 'LANDING_PAGE',
    ai_auto_respond: false,
    inspection_date: new Date(Date.now() - 9 * 86400000).toISOString(),
    inspection_notes: 'Insurance claim settled at $31,500. Materials delivered on site.',
    quote_amount: 31500,
    job_value: 31500,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'preview-14',
    full_name: 'Samantha Hayes',
    phone: '+1 (469) 555-0164',
    email: 'samantha.hayes@planorealtors.com',
    zip_code: '75025',
    address: '3200 Coit Rd, Plano, TX',
    issue_type: 'ROOF_REPLACEMENT',
    roof_age: '10-20 years',
    has_insurance_claim: false,
    status: 'JOB_WON',
    source: 'GOOGLE',
    ai_auto_respond: false,
    inspection_date: new Date(Date.now() - 14 * 86400000).toISOString(),
    inspection_notes: 'Installation 100% completed & final payment collected. 5-Star Google review received!',
    quote_amount: 16800,
    job_value: 16800,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
];

export const PREVIEW_STATS: Stats = {
  totalLeads: 58,
  todayLeads: 6,
  weekLeads: 24,
  pipeline: {
    NEW: 3,
    AI_QUALIFYING: 3,
    INSPECTION_SCHEDULED: 3,
    QUOTE_SENT: 2,
    JOB_WON: 3,
  },
  sources: { LANDING_PAGE: 22, MISSED_CALL: 16, GOOGLE: 12, REFERRAL: 8 },
  revenue: { totalQuoted: 218450, totalWon: 114680, conversionRate: 34.2 },
  missedCalls: 6,
  totalMessages: 184,
};

export const PREVIEW_MESSAGES: Record<string, Message[]> = {
  'preview-1': [
    {
      id: 'm1-1',
      lead_id: 'preview-1',
      role: 'assistant',
      content: 'Hey Sarah! This is Sarah from Apex Roofing & Restoration. Sorry we missed your call a moment ago, our estimators are currently on a roof. Are you experiencing an active leak or need a free storm inspection?',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 8 * 60000).toISOString(),
    },
    {
      id: 'm1-2',
      lead_id: 'preview-1',
      role: 'user',
      content: 'Hi! Yes, we have water dripping from the master closet ceiling right next to the chimney brick. It started during the heavy rain an hour ago.',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 6 * 60000).toISOString(),
    },
    {
      id: 'm1-3',
      lead_id: 'preview-1',
      role: 'assistant',
      content: 'Got it Sarah, chimney leaks can cause fast drywall damage. We have an emergency crew in Frisco right now. What is your home address?',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 5 * 60000).toISOString(),
    },
    {
      id: 'm1-4',
      lead_id: 'preview-1',
      role: 'user',
      content: 'We are at 6824 Windward Way in Frisco. Can someone come tarp it or inspect it today or tomorrow morning?',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 4 * 60000).toISOString(),
    },
    {
      id: 'm1-5',
      lead_id: 'preview-1',
      role: 'assistant',
      content: 'Yes! Our senior field estimator Marcus Vance can be there tomorrow morning at 10:00 AM with tarping materials and high-res drone cameras. Does 10:00 AM work for you?',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 3 * 60000).toISOString(),
    },
    {
      id: 'm1-6',
      lead_id: 'preview-1',
      role: 'user',
      content: 'Yes please, 10:00 AM works perfectly! Thank you so much for responding so quickly.',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 2 * 60000).toISOString(),
    },
    {
      id: 'm1-7',
      lead_id: 'preview-1',
      role: 'contractor',
      content: 'You got it Sarah! Alex from the Apex office here. Marcus has you on his route tomorrow at 10 AM sharp. If the drip speeds up before then, place a bucket under it and call us right back!',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 1 * 60000).toISOString(),
    },
  ],
  'preview-4': [
    {
      id: 'm4-1',
      lead_id: 'preview-4',
      role: 'assistant',
      content: 'Hi Marcus! Thanks for reaching out to Apex Roofing via our online estimate portal. We see you selected storm hail damage in Plano (75024). Has an insurance claim been filed yet?',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 95 * 60000).toISOString(),
    },
    {
      id: 'm4-2',
      lead_id: 'preview-4',
      role: 'user',
      content: 'Yes, State Farm claim #SF-98421. The adjuster is coming next Thursday. I want a contractor on site with me so they don\'t underpay.',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 50 * 60000).toISOString(),
    },
    {
      id: 'm4-3',
      lead_id: 'preview-4',
      role: 'assistant',
      content: 'Smart move. Having our HAAG-certified inspector meet the adjuster ensures every hail bruise, gutter dent, and soft metal damage is included on their scope. Would you like our specialist Jason Miller to attend?',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 48 * 60000).toISOString(),
    },
    {
      id: 'm4-4',
      lead_id: 'preview-4',
      role: 'user',
      content: 'Definitely. How much do you charge to do the inspection and walk with the adjuster?',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    },
    {
      id: 'm4-5',
      lead_id: 'preview-4',
      role: 'assistant',
      content: 'Our comprehensive storm inspection, drone photographic evidence report, and adjuster walkthrough are 100% free with zero upfront cost. Let\'s get your address locked in!',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 20 * 60000).toISOString(),
    },
  ],
  'preview-7': [
    {
      id: 'm7-1',
      lead_id: 'preview-7',
      role: 'assistant',
      content: 'Hi Emily! Your roof inspection is confirmed for tomorrow, Tuesday at 10:00 AM at 3819 Willow Bend Dr, West Plano. Estimator Marcus Vance will be in an Apex Roofing vehicle.',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    },
    {
      id: 'm7-2',
      lead_id: 'preview-7',
      role: 'user',
      content: 'Thank you! The gate code is #4412. Will Marcus need access to the attic as well?',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    },
    {
      id: 'm7-3',
      lead_id: 'preview-7',
      role: 'contractor',
      content: 'Thanks for the gate code Emily! Yes, Marcus will do a quick 5-minute attic check to inspect decking wood and moisture levels. See you tomorrow at 10 AM!',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    },
  ],
  'preview-10': [
    {
      id: 'm10-1',
      lead_id: 'preview-10',
      role: 'contractor',
      content: 'Hi David! Marcus just finished compiling your itemized roofing estimate for 4115 Belt Line Rd. You can review the scope, 50-year warranty options, and pricing here: https://apexroofing.com/q/77102',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'm10-2',
      lead_id: 'preview-10',
      role: 'user',
      content: 'Looks very thorough! Is the $18,450 total including the removal of our old two layers of shingles?',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'm10-3',
      lead_id: 'preview-10',
      role: 'contractor',
      content: 'Yes sir, complete 2-layer tear-off, synthetic ice & water shield, high-profile ridge caps, and magnetic ground sweep for nails are all included in that price.',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 6 * 3600000).toISOString(),
    },
  ],
  'preview-12': [
    {
      id: 'm12-1',
      lead_id: 'preview-12',
      role: 'assistant',
      content: 'Congratulations Jennifer! Your digital agreement for 7204 Stonebrook Pkwy has been verified and e-signed. Project value: $23,780.00.',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: 'm12-2',
      lead_id: 'preview-12',
      role: 'user',
      content: 'Awesome! We paid the 50% deposit via the Stripe link ($11,890.00). What time will the crew arrive Friday?',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'm12-3',
      lead_id: 'preview-12',
      role: 'contractor',
      content: 'Deposit confirmed and receipt emailed! Crew Alpha will arrive Friday at 7:30 AM. Dump trailer will be placed on the left side of the driveway. You\'re going to love the new Onyx Black shingles!',
      channel: 'sms',
      twilio_sid: null,
      created_at: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
};

export const PREVIEW_MISSED_CALLS = [
  {
    id: 'mc-1',
    caller_phone: '+1 (214) 555-0138',
    call_status: 'No Answer / Dropped Call',
    count: 1,
    textback_sent: true,
    textback_message: 'Hey Sarah! This is Sarah from Apex Roofing & Restoration. Sorry we missed your call a moment ago, our estimators are currently on a roof. Are you experiencing an active leak or need a free storm inspection?',
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 'mc-2',
    caller_phone: '+1 (214) 555-0193',
    call_status: 'Busy Line / In Field',
    count: 2,
    textback_sent: true,
    textback_message: 'Hey! Sorry we missed you, all lines are currently assisting homeowners affected by Tuesday\'s storm. Reply with your city or leak details and we\'ll prioritize your spot!',
    created_at: new Date(Date.now() - 140 * 60000).toISOString(),
  },
  {
    id: 'mc-3',
    caller_phone: '+1 (214) 555-0119',
    call_status: 'After-Hours Auto Attendant',
    count: 1,
    textback_sent: true,
    textback_message: 'Thanks for calling Apex Roofing! Our dispatch office opens at 7:30 AM. Reply CALL to schedule an early morning roof check, or tell us what you need here.',
    created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'mc-4',
    caller_phone: '+1 (972) 555-0162',
    call_status: 'Dropped Call',
    count: 1,
    textback_sent: true,
    textback_message: 'Hi there! We missed your call at Apex Roofing. How can our team help you with your roof today?',
    created_at: new Date(Date.now() - 18 * 3600000).toISOString(),
  },
  {
    id: 'mc-5',
    caller_phone: '+1 (469) 555-0144',
    call_status: 'Customer Hung Up',
    count: 1,
    textback_sent: true,
    textback_message: 'Hey, this is Sarah with Apex Roofing. Saw you called earlier — do you need a quick repair estimate or storm inspection?',
    created_at: new Date(Date.now() - 26 * 3600000).toISOString(),
  },
  {
    id: 'mc-6',
    caller_phone: '+1 (214) 555-0176',
    call_status: 'Voicemail Received',
    count: 3,
    textback_sent: true,
    textback_message: 'Hi Mark, got your voicemail regarding your gutter replacement! Estimator Marcus will text you with our schedule shortly.',
    created_at: new Date(Date.now() - 40 * 3600000).toISOString(),
  },
];

export const PREVIEW_CRM_DATA = {
  teamMembers: [
    {
      id: 'team-1',
      name: 'Sarah Connor (AI Assistant)',
      role: '24/7 AI Voice & SMS Dispatcher',
      phone: '+1 (214) 555-0199',
      email: 'ai-dispatch@apexroofing.com',
      status: '⚡ 24/7 AI System Active',
      active_jobs: 14,
      quoted_volume: '$218,450',
      conversion_rate: '34.2%',
      certifications: ['Telnyx AI Engine', 'Real-Time Voice & SMS', 'Zero-Latency Dispatch'],
    },
    {
      id: 'team-2',
      name: 'Marcus Vance',
      role: 'Senior Field Estimator & Hail Specialist',
      phone: '+1 (214) 555-0144',
      email: 'marcus@apexroofing.com',
      status: '🟢 Active in Field (On-Duty)',
      active_jobs: 4,
      quoted_volume: '$74,200',
      conversion_rate: '48.5%',
      certifications: ['HAAG Certified Residential Inspector', 'OSHA 30 Safety', 'Part 107 Commercial Drone Pilot'],
    },
    {
      id: 'team-3',
      name: 'Diego Ramirez',
      role: 'Production Crew Supervisor (Crew Alpha)',
      phone: '+1 (469) 555-0188',
      email: 'diego@apexroofing.com',
      status: '🟢 On Jobsite (Active Crew)',
      active_jobs: 3,
      quoted_volume: '$55,280',
      conversion_rate: '100% On-Time',
      certifications: ['Owens Corning Platinum Master', 'CertainTeed Shingle Master', 'Fall Protection Supervisor'],
    },
    {
      id: 'team-4',
      name: 'Jason Miller',
      role: 'Insurance Claim & Adjuster Liaison',
      phone: '+1 (972) 555-0163',
      email: 'jason@apexroofing.com',
      status: '🟡 In Adjuster Meeting',
      active_jobs: 5,
      quoted_volume: '$89,400',
      conversion_rate: '62.0%',
      certifications: ['Xactimate Level 3 Certified', 'Public Adjuster Liaison', 'HAAG Wind & Hail Specialist'],
    },
  ],
  calendarEvents: [
    {
      id: 'cal-1',
      lead_id: 'preview-1',
      day: 'Tue (Tomorrow)',
      time_slot: '10:00 AM - 11:15 AM',
      title: 'Emergency Chimney Tarp & Moisture Scan',
      client_name: 'Sarah Mitchell',
      location: '6824 Windward Way, Frisco, TX',
      estimator: 'Marcus Vance · Senior Estimator',
      event_type: 'storm',
    },
    {
      id: 'cal-2',
      lead_id: 'preview-8',
      day: 'Tue (Tomorrow)',
      time_slot: '2:30 PM - 3:45 PM',
      title: 'Allstate Insurance Adjuster Walkthrough',
      client_name: 'Robert Henderson',
      location: '1904 Breckinridge Blvd, Richardson, TX',
      estimator: 'Jason Miller · Insurance Liaison',
      event_type: 'storm',
    },
    {
      id: 'cal-3',
      lead_id: 'preview-7',
      day: 'Mon (Today)',
      time_slot: '1:00 PM - 2:15 PM',
      title: 'Drone Roof Scan & Attic Wood Assessment',
      client_name: 'Emily Carter',
      location: '3819 Willow Bend Dr, West Plano, TX',
      estimator: 'Marcus Vance · Senior Estimator',
      event_type: 'residential',
    },
    {
      id: 'cal-4',
      lead_id: 'preview-9',
      day: 'Wed (Jul 24)',
      time_slot: '11:00 AM - 12:15 PM',
      title: 'Pipe Collar Flashing Leak Repair Survey',
      client_name: 'Kevin Nguyen',
      location: '1422 Kelly Blvd, Carrollton, TX',
      estimator: 'Diego Ramirez · Supervisor',
      event_type: 'residential',
    },
    {
      id: 'cal-5',
      lead_id: 'preview-12',
      day: 'Fri (Jul 26)',
      time_slot: '7:30 AM - 5:00 PM',
      title: 'Crew Alpha: Full Roof Replacement Installation',
      client_name: 'Jennifer Lee',
      location: '7204 Stonebrook Pkwy, Frisco, TX',
      estimator: 'Crew Alpha (6 Men) · Diego Ramirez',
      event_type: 'residential',
    },
    {
      id: 'cal-6',
      lead_id: 'preview-13',
      day: 'Sat (Jul 27)',
      time_slot: '8:00 AM - 4:00 PM',
      title: 'Crew Bravo: Standing Seam Metal Accent Installation',
      client_name: 'Brian O\'Connor',
      location: '2908 Eldorado Pkwy, Little Elm, TX',
      estimator: 'Crew Bravo · Diego Ramirez',
      event_type: 'storm',
    },
  ],
  quotes: [
    {
      id: 'quote-101',
      lead_id: 'preview-12',
      client_name: 'Jennifer Lee',
      phone: '+1 (469) 555-0113',
      zip_code: '75035',
      squares: 36,
      pitch: '7/12',
      tier: '50-Year Architectural Shingle (Owens Corning Duration)',
      amount: '$23,780',
      total_quote: 23780,
      status: 'Approved & Contract Signed',
      created_at: new Date(Date.now() - 4 * 86400000).toLocaleDateString(),
    },
    {
      id: 'quote-102',
      lead_id: 'preview-10',
      client_name: 'David Ramirez',
      phone: '+1 (214) 555-0166',
      zip_code: '75001',
      squares: 28,
      pitch: '6/12',
      tier: 'Class 4 Impact Resistant Shingle (OC Storm Duration)',
      amount: '$18,450',
      total_quote: 18450,
      status: 'Sent via SMS · Viewed by Homeowner',
      created_at: new Date(Date.now() - 2 * 86400000).toLocaleDateString(),
    },
    {
      id: 'quote-103',
      lead_id: 'preview-11',
      client_name: 'Patricia Davis',
      phone: '+1 (972) 555-0177',
      zip_code: '75078',
      squares: 38,
      pitch: '8/12',
      tier: '50-Year Architectural Shingle (Owens Corning Duration)',
      amount: '$24,200',
      total_quote: 24200,
      status: 'Sent via SMS',
      created_at: new Date(Date.now() - 1 * 86400000).toLocaleDateString(),
    },
    {
      id: 'quote-104',
      lead_id: 'preview-13',
      client_name: 'Brian O\'Connor',
      phone: '+1 (214) 555-0182',
      zip_code: '75068',
      squares: 46,
      pitch: '6/12',
      tier: 'Standing Seam Metal + Architectural Combo',
      amount: '$31,500',
      total_quote: 31500,
      status: 'Approved & In Production',
      created_at: new Date(Date.now() - 8 * 86400000).toLocaleDateString(),
    },
  ],
  contracts: [
    {
      id: 'cnt-1',
      lead_id: 'preview-12',
      client_name: 'Jennifer Lee',
      phone: '+1 (469) 555-0113',
      zip_code: '75035',
      contract_type: 'Storm Contingency & 50-Year Roof Agreement',
      amount: '$23,780.00',
      status: 'Signed (E-Signed & Locked)',
      signed_date: 'Signed 2 days ago · IP Verified',
    },
    {
      id: 'cnt-2',
      lead_id: 'preview-13',
      client_name: 'Brian O\'Connor',
      phone: '+1 (214) 555-0182',
      zip_code: '75068',
      contract_type: 'Full Residential Replacement Agreement',
      amount: '$31,500.00',
      status: 'Signed (E-Signed & Locked)',
      signed_date: 'Signed 4 days ago · IP Verified',
    },
    {
      id: 'cnt-3',
      lead_id: 'preview-10',
      client_name: 'David Ramirez',
      phone: '+1 (214) 555-0166',
      zip_code: '75001',
      contract_type: 'Storm Contingency Agreement',
      amount: '$18,450.00',
      status: 'Pending Homeowner Signature',
      signed_date: 'Sent via SMS Link',
    },
    {
      id: 'cnt-4',
      lead_id: 'preview-11',
      client_name: 'Patricia Davis',
      phone: '+1 (972) 555-0177',
      zip_code: '75078',
      contract_type: 'Standard Residential Replacement',
      amount: '$24,200.00',
      status: 'Pending Homeowner Signature',
      signed_date: 'Delivered to Mobile',
    },
  ],
  invoices: [
    {
      id: 'INV-2026-081',
      lead_id: 'preview-12',
      client_name: 'Jennifer Lee',
      phone: '+1 (469) 555-0113',
      zip_code: '75035',
      invoice_date: 'Jul 18, 2026',
      due_date: 'Jul 25, 2026',
      total_scope: '$23,780.00',
      amount_due: '$11,890.00',
      description: 'Draw #1: 50% Material Deposit & Mobilization',
      status: 'Paid in Full (Stripe)',
    },
    {
      id: 'INV-2026-079',
      lead_id: 'preview-13',
      client_name: 'Brian O\'Connor',
      phone: '+1 (214) 555-0182',
      zip_code: '75068',
      invoice_date: 'Jul 14, 2026',
      due_date: 'Jul 21, 2026',
      total_scope: '$31,500.00',
      amount_due: '$15,750.00',
      description: 'Initial Insurance ACV Check Deposit',
      status: 'Paid in Full (ACH)',
    },
    {
      id: 'INV-2026-074',
      lead_id: 'preview-14',
      client_name: 'Samantha Hayes',
      phone: '+1 (469) 555-0164',
      zip_code: '75025',
      invoice_date: 'Jul 08, 2026',
      due_date: 'Jul 15, 2026',
      total_scope: '$16,800.00',
      amount_due: '$16,800.00',
      description: 'Final Completion & Manufacturer Warranty Release',
      status: 'Paid in Full (Stripe)',
    },
    {
      id: 'INV-2026-085',
      lead_id: 'preview-10',
      client_name: 'David Ramirez',
      phone: '+1 (214) 555-0166',
      zip_code: '75001',
      invoice_date: 'Jul 20, 2026',
      due_date: 'Jul 27, 2026',
      total_scope: '$18,450.00',
      amount_due: '$9,225.00',
      description: 'Draw #1: 50% Project Commitment Deposit',
      status: 'Pending Payment',
    },
  ],
  payments: [
    {
      id: 'PAY-9041',
      invoice_id: 'INV-2026-081',
      client_name: 'Jennifer Lee',
      amount: '$11,890.00',
      payment_method: '💳 Stripe · Visa ending in 4242',
      reference: 'ch_3Lz9X2F8q1k9',
      status: 'Settled & Transferred',
      paid_at: '2 days ago',
    },
    {
      id: 'PAY-9038',
      invoice_id: 'INV-2026-079',
      client_name: 'Brian O\'Connor',
      amount: '$15,750.00',
      payment_method: '🏦 Direct ACH Transfer (Chase Bank)',
      reference: 'ach_tx_881920',
      status: 'Settled & Transferred',
      paid_at: '4 days ago',
    },
    {
      id: 'PAY-9022',
      invoice_id: 'INV-2026-074',
      client_name: 'Samantha Hayes',
      amount: '$16,800.00',
      payment_method: '💳 Stripe · Mastercard ending in 8821',
      reference: 'ch_3Lw8A1F1x7q3',
      status: 'Settled & Transferred',
      paid_at: '12 days ago',
    },
  ],
  photos: [
    {
      id: 'p-1',
      lead_id: 'preview-1',
      client_name: 'Sarah Mitchell',
      zip_code: '75034',
      date_added: 'Yesterday',
      before_url: '/images/storm.png',
      before_caption: 'Pre-inspection drone scan: Severe hail impact fractures along north roof slope and chimney flashing separation.',
      after_url: '/images/finished.png',
      after_caption: 'Post-restoration: Complete Owens Corning 50-Year architectural system with custom chimney counter-flashing and ice & water shield.',
    },
    {
      id: 'p-2',
      lead_id: 'preview-4',
      client_name: 'Marcus Johnson',
      zip_code: '75024',
      date_added: '3 days ago',
      before_url: '/images/storm.png',
      before_caption: 'Field audit: 18 documented hail strikes per 100 sq ft test square. Substantial granule loss exposing fiberglass base.',
      after_url: '/images/finished.png',
      after_caption: 'Post-restoration: Class 4 impact resistant shingles installed with high-ventilation ridge cap system.',
    },
    {
      id: 'p-3',
      lead_id: 'preview-12',
      client_name: 'Jennifer Lee',
      zip_code: '75035',
      date_added: '1 week ago',
      before_url: '/images/storm.png',
      before_caption: 'Pre-restoration: 22-year-old weathered 3-tab shingles with wind uplift and exposed nail heads.',
      after_url: '/images/finished.png',
      after_caption: 'Post-restoration: Architectural dimensional shingles in Onyx Black with seamless 6-inch aluminum gutters.',
    },
  ],
  reviews: [
    {
      id: 'rev-1',
      lead_id: 'preview-1',
      author: 'Sarah Mitchell',
      client_name: 'Sarah Mitchell',
      location: 'Frisco, TX (75034)',
      rating: 5,
      date: 'Yesterday',
      source: 'Google Business Profile',
      text: 'Apex Roofing responded within 3 minutes of our missed call after the storm! Estimator Marcus was out with a drone, identified 14 hail bruises, and tarped our chimney immediately. Outstanding customer care!',
      verified_job: 'Emergency Leak Mitigation & Roof Replacement',
    },
    {
      id: 'rev-2',
      lead_id: 'preview-12',
      author: 'Jennifer Lee',
      client_name: 'Jennifer Lee',
      location: 'Frisco, TX (75035)',
      rating: 5,
      date: '3 days ago',
      source: 'Google Business Profile',
      text: 'The best roofing experience we have ever had. Everything was handled on our phones — we approved the quote via SMS, signed the contract online, and the crew replaced the entire roof in ONE day. Cleaned up every nail!',
      verified_job: '50-Year Architectural Shingle Replacement',
    },
    {
      id: 'rev-3',
      lead_id: 'preview-14',
      author: 'Samantha Hayes',
      client_name: 'Samantha Hayes',
      location: 'Plano, TX (75025)',
      rating: 5,
      date: '1 week ago',
      source: 'Google Business Profile',
      text: 'As a local realtor, I recommend Apex Roofing to all my clients. Their photo reports are accepted immediately by insurance adjusters without any hassle. True 5-star roofing company.',
      verified_job: 'Insurance Storm Damage Restoration',
    },
    {
      id: 'rev-4',
      lead_id: 'preview-13',
      author: 'Brian O\'Connor',
      client_name: 'Brian O\'Connor',
      location: 'Little Elm, TX (75068)',
      rating: 5,
      date: '2 weeks ago',
      source: 'Facebook Recommendations',
      text: 'Super professional team. The text updates kept us informed at every step. Diego and Crew Alpha were punctual, polite, and did flawless work on our steep roof.',
      verified_job: 'Full Tear-Off & Standing Seam Metal Accent',
    },
  ],
};

export const PREVIEW_SETTINGS: ContractorSettings = {
  id: 'apex-settings-1',
  company_name: 'Apex Roofing & Restoration',
  company_phone: '+1 (214) 555-0188',
  service_area: 'Dallas-Fort Worth Metroplex (Plano, Frisco, McKinney, Allen, Addison)',
  google_review_link: 'https://g.page/r/apex-roofing-dfw/review',
  ai_greeting_template: 'Hi! This is Sarah with {{company}}. How can we help with your roof today?',
  missed_call_template: 'Hey, this is Sarah from Apex Roofing! Sorry I missed your call, I was on a roof. Are you experiencing a leak or do you need a free storm inspection?',
  telnyx_phone_number: '+1 (214) 555-0199',
  telnyx_messaging_profile_id: 'prof_4019a8e2_apex',
  telnyx_texml_app_id: 'texml_app_99120_apex',
  telnyx_ai_assistant_id: 'asst_telnyx_sarah_v2',
  telnyx_public_key: 'pk_telnyx_live_901848201a',
  roofer_phone_number: '+1 (214) 555-0100',
  business_days: [1, 2, 3, 4, 5],
  business_start: '07:30',
  business_end: '18:30',
  business_timezone: 'America/Chicago',
  ring_timeout_seconds: 18,
};
